version: '3.7'

networks:
  subsidia-network:
    external: true
    driver: overlay

secrets:
  mongodb-root-username:
    external: true
  mongodb-root-password:
    external: true
  mailtrap_token:
    external: true
  XRapidAPIKey:
    external: true

services:
  backend:
    secrets:
      - mongodb-root-username
      - mongodb-root-password
      - mailtrap_token
      - XRapidAPIKey
    image: buddy-budget:2.1.2
    ports:
      - "8317:5555"
    environment:
      - MONGO_HOST=mongodb:27017
      - mongodb_username=/run/secrets/mongodb-root-username
      - mongodb_password=/run/secrets/mongodb-root-password
      - mailtrap_token=/run/secrets/mailtrap_token
      - XRapidAPIKey=/run/secrets/XRapidAPIKey
    deploy:
      replicas: 5
      placement:
        constraints: [node.role == manager]
    networks:
      - subsidia-network
      
  stock_manager:
    secrets:
      - mongodb-root-username
      - mongodb-root-password
    image: buddy-budget:2.1.2
    environment:
      - MONGO_HOST=mongodb:27017
      - mongodb_username=/run/secrets/mongodb-root-username
      - mongodb_password=/run/secrets/mongodb-root-password
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    networks:
      - subsidia-network